### ISSUE TITLE
Add Icon/Indicator For "Drag n Use" Scripts

### ISSUE THREAD

**Issue by patflannery** [patflannery/unity-awesomeness#4]
Add some visual indicator for simple scripts, like camera follow. For scripts without reliances on other objects/scripts.

**Comment by mhulse** [comment]
Does Unity have any in-app icons? Maybe we could use those?

**Comment by patflannery** [comment]
Hmm, thought about this some more - rather than indicating this visually somewhere, I think each script should have a comment header describing use. Also, almost all scripts have some sort of requirements or instructions, so why not presume that they all need explanation. Making new issue for that, closing this one.
