### ISSUE TITLE
Fix links due to username change

### ISSUE THREAD

**Issue by mhulse** [patflannery/unity-awesomeness#7]
In README.md

**Comment by mhulse** [comment]
Currently, links look like:

https://github.com/pflannery111/unity-starters/blob/master/Misc/generateobjects.js

I think I'll change that to relative links, like:

<Misc/generateobjects.js>

It's not the raw version, but it makes it easier to link to things.

**Comment by patflannery** [comment]
Per a discussion earlier this week, I believe Micky did this. Closing.

**Comment by mhulse** [comment]
Doh, sorry, forgot to close this. Thanks @patflannery!
